version: "3.6"

networks:
  keycloak:
    ipam:
      driver: default
      config:
        - subnet: 192.168.57.0/24

# volumes:
#   pgdata:
  # grafana-storage: {}

services:

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.4
    hostname: keycloak
    container_name: keycloak
    command:
      - start-dev
      - --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_PORT=5432
      - KC_DB_URL_DATABASE=postgres
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
      # - KC_HOSTNAME=localhost
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks: 
      - keycloak

  postgres:
    image: postgres:15
    hostname: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # PGDATA: /var/lib/postgresql/data/pgdata
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks: 
      - keycloak

  grafana:
    image: grafana/grafana-oss
    hostname: grafana
    container_name: grafana
    environment:
      GF_SERVER_ROOT_URL: 'http://127.0.0.1:3000/'
      GF_INSTALL_PLUGINS: 'grafana-clock-panel, grafana-simple-json-datasource'
    volumes:
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      # - 'grafana-storage:/var/lib/grafana'
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks: 
      - keycloak

  prometheus:
    image: quay.io/prometheus/prometheus
    hostname: prometheus
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks: 
      - keycloak

  openldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    command:
      - --copy-service
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "DevOps Sandbox Inc."
      LDAP_DOMAIN: "devops-sandbox.org"
      LDAP_BASE_DN: ""
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "config"
      LDAP_TLS: "false"
      LDAP_REPLICATION: "false"
    volumes:
      - ./config/ldap_sample.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    ports:
      - "8389:389"
      - "8636:636"
    networks: 
      - keycloak

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "9080:80"
    depends_on:
      - openldap
    networks: 
      - keycloak



